### ISSUE TITLE
Jpeg error

### ISSUE THREAD

**Issue by JimWebster** [ivmartel/dwv-orthanc-plugin#1]
greetings - I compiled the plugin (0.8.0 Beta appears) successfully and can view some files. But ... many images give an error: "Error: Unsupported DICOM transfer syntax (JPEG): 1.2.840.10008.1.2.4.70."

Orthanc version is 0.8.5. Window levelling also does not seem to work.

**Comment by ivmartel** [comment]
Hi, the beta is weird, if you are using the latest code, it should not appear.
About JPEG, sorry, but it is not supported yet, I'm still looking for a jpeg javascript library that supports the strange DICOM jpegs... See this page for the supported formats: https://github.com/ivmartel/dwv/wiki/Dicom-Support
About window levelling, so what happens? Which browser are you using?
