### ISSUE TITLE
Error: Not a valid DICOM file (no magic DICM word found).

### ISSUE THREAD

**Issue by 6Beaufort** [ivmartel/dwv-orthanc-plugin#10]
here is the file that leads to that error
https://www.dropbox.com/s/dve5lpjfnxtcsw1/5f19601c-3e5fa872-e566e9f2-36aa3b31-dc719c3e%20%281%29.zip?dl=0

**Comment by ivmartel** [comment]
In theory all DICOM files should start with the prefix `DICM`. See this [error](https://github.com/ivmartel/dwv/wiki/Error-Messages#not-a-valid-dicom-file) page on the dwv wiki.
Your file does not contain this prefix which is why you get this error.
