### ISSUE TITLE
DWV Integration with ORTHANC

### ISSUE THREAD

**Issue by jagjotwadali** [ivmartel/dwv-orthanc-plugin#23]
Hi @ivmartel 

I have three questions 

1. I had installed dwv -orthanc plugin and it was working fine .When I restarted the orthanc server again ,the plugin was not displaying in orthanc explorer.what I have to do?

1. Currently ,I had integrated dwv dicom viewer into a telemedicine application(developed in .net framework). user can upload JPEG /DICOM image and then he/she can view the image/annotated image in the dicom viewer and can send it to the doctor .The doctor can view the image/annotated image .Now DWV is working without any PACS or dicom server .I want the functionality of DICOM viewer and PACS server in my telemedicine application .My question to you is it possible to integrate orthanc dwv plugin with the telemedicine application .I do not have much idea about PACS server .In my understanding orthanc is a dicom server or mini pacs .

1. I tried to upload the JPEG images in orthanc but it was a failure. I want to ask what is jpeg encoded dicoms ?

**Comment by ivmartel** [comment]
In case it is not too late, a few quick answers:
1. Are you sure you launched it with a configuration that included the dwv-orthanc-plugin in the plugin section?
1. Orthanc is a simple PACS and could be used in you application, now you would have to connect both. Not sure what your app does so I can't tell much more.
1. The pixel content of a dicom can come un-encoded (the raw pixel values) or encoded. Jpeg is one of the encoding, DICOM also supports Jpeg2000. Othanc and dwv should support both.

**Comment by ivmartel** [comment]
Closing for now. Feel free to comment!
